# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Sheri's Blog

description: Student Learning Tracker
author:
  name: Sheri
  email: sheriyar.nawaz@challoners.org
  github: SheriNawaz786
  twitter: NONE
  pinterest: NONE
  linkedin: NONE
  bio: Some random student from the UK
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
